### ISSUE TITLE
PBS scripts erroneously pass data directory as argument to `HealthGPS.Console`

### ISSUE THREAD

**Issue by alexdewar** [imperialCHEPI/healthgps-examples#15]
As I changed the config files to use a URL for the data source, if a user also passes in the path to the data folder then they will get an error (I think this may already have bitten @jzhu20). We should update the scripts to drop this argument.

**Comment by jamesturner246** [comment]
Sounds sensible. Mixing up methods probably will confuse people.

**Comment by alexdewar** [comment]
Having looked at these scripts more closely, I've just noticed that they won't work out of the box, because they contain paths to directories outside this repo. For example, `example-india.pbs` is looking for a config file in `$HOME/healthgps/example_india_indianinput`. Really, for this to be a useful example, it should use the config files in the same folder as the script, otherwise it'll be more confusing than helpful to new users. If these scripts are just an artifact of @jzhu20's setup, I think we should delete them, but if we actually expect them to be used (e.g. by people joining the lab) they should work without additional tinkering.

Thoughts? @jamesturner246 @jzhu20
