### ISSUE TITLE
`ompthreads` doesn't match `ncpus` in PBS scripts?

### ISSUE THREAD

**Issue by alexdewar** [imperialCHEPI/healthgps-examples#18]
https://github.com/imperialCHEPI/healthgps-examples/blob/c2adf449ff63041d08f676d2a7659e0301aff01e/HLM_India/example-india.pbs#L2

@jamesturner246 @jzhu20 I'm working on #17 and just noticed this... Is there any reason why the number of OMP threads is set to much lower than the number of CPUs here? Surely this just means that most CPUs are sitting idle?

**Comment by jamesturner246** [comment]
I convinced myself a little while back that TBB doesn't use `ompthreads` at all, so I don't even think it should be there. This might change if/when we move to Eigen though.

**Comment by alexdewar** [comment]
Does changing this parameter affect the `OMP_THREAD_LIMIT` env var? Because HGPS does make use of that.

**Comment by jamesturner246** [comment]
Oh yes, kinda gross but I used `OMP_THREAD_LIMIT` to set TBB's thread limit. There's almost certainly a cleaner way.

When I looked into PBS's `ompthreads`, it wasn't immediately clear which `OMP_THREAD_....` var is being set, as there's a few of them, and I couldn't work out which one PBS sets. See `OMP_NUM_THREADS` and `OMP_THREAD_LIMIT` in https://www.openmp.org/spec-html/5.0/openmpch6.html.

If you have a cleaner way in mind, go for it.

**Comment by alexdewar** [comment]
I had a look on the [RCS HPC documentation](https://icl-rcs-user-guide.readthedocs.io/en/latest/hpc/getting-started/) and there was disappointingly little info about the PBS flags. So I ran an experiment to see which env vars are *actually* set and it turns out that setting `ompthreads` affects the `OMP_NUM_THREADS` var, but `OMP_THREAD_LIMIT` doesn't appear to be set. Does this mean we have a bug in HGPS? Really we want to respect this variable. (Or do we want users to be able to set the thread limit via a command-line argument instead? Might be more explicit.)

In relation to the original issue, it looks like all the examples of PBS scripts on the documentation suggest setting `ompthreads` to `ncpus`, so I assume it was just an oversight... not that this flag actually affects HGPS as it stands!
